import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  containerForLogoName: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#BFDAF9',
  },
  authContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'start',
    alignItems: 'center',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    backgroundColor: '#EBEDFF',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
  },
  containerLogoName: {
    width: '100%',
    height: 160,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  textWelcome: {
    fontFamily: 'Poppins-ExtraBold',
    fontSize: 32,
    color: '#4E73DF',
  },
  buttonLoginBorder: {
    width: 300,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 130,
    backgroundColor: '#4E73DF',
    borderRadius: 15,
  },
  buttonRegisterBorder: {
    width: 300,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
    backgroundColor: '#CECECE',
    borderRadius: 15,
  },
  btnText: {
    color: '#FFFFFF',
    fontFamily: 'Poppins-ExtraBold',
    fontSize: 32,
  },
  btnAuthText: {
    color: '#FFFFFF',
    fontFamily: 'Poppins-Bold',
    fontSize: '26',
  },
  bottomInfo: {
    width: '100%',
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E4E4E4',
    marginTop: 120,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
  },
  textBottomInfo: {
    fontFamily: 'Poppins-Regular',
    fontSize: 14,
    color: '#777777',
  },
  labelAuthProperty: {
    fontFamily: 'Poppins-Light',
    fontSize: 14,
    color: '#858796',
    marginBottom: 10,
    marginTop: 10,
    marginStart: 10,
  },
  containerAuthField: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  borderAuthField: {
    width: 300,
    height: 40,
    alignItems: 'center',
    paddingStart: 15,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 15,
  },
  inputAuthField: {
    flex: 1,
    width: '100%',
    fontSize: 14,
    fontFamily: 'Poppins-Regular',
    color: '#858796',
  },
  authSubmitButton: {
    width: 190,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    borderRadius: 15,
    backgroundColor: '#4E73DF',
    borderWidth: 1,
    borderColor: '#D0D0D0',
  },
  authSubmitButtonClickableArea: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  containerAskText: {
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: 15,
    flexDirection: 'row',
  },
  askText: {
    fontFamily: 'Poppins-Regular',
    fontSize: 10,
    color: '#858796',
  },
  askTextButton: {
    fontFamily: 'Poppins-Regular',
    fontSize: 12,
    color: '#4E73DF',
    marginStart: 5,
  },
})